/**
 * Catalog build: validated recipe JSON → parsed ingredients → idempotent seed SQL.
 *
 * Every seeded recipe gets structured ingredients with `normalized_name`, `preparation` and
 * `grocery_section`, so the grocery list and prep plan work out of the box. Seeds are safe to
 * re-run: recipes upsert by slug, and their ingredients and steps are replaced.
 */
import { ASSUMED_ON_HAND } from "../domain/ingredient-data";
import { parseIngredientList } from "../domain/ingredients";
import { catalogRecipeSchema, type CatalogRecipe } from "./schema";

export type CatalogIssue = { slug: string; message: string };

export type CatalogBuild = {
  recipes: CatalogRecipe[];
  sql: string;
  issues: CatalogIssue[];
};

export const catalogImagePath = (slug: string) => `/images/recipes/${slug}.svg`;

const str = (value: string | null | undefined) =>
  value === null || value === undefined ? "null" : `'${value.replace(/'/g, "''")}'`;
const num = (value: number | null | undefined) =>
  value === null || value === undefined ? "null" : String(value);
const arr = (values: string[]) => `array[${values.map(str).join(", ")}]::text[]`;

/** Validates a parsed JSON value as a list of catalog recipes; throws with every problem listed. */
export function parseCatalog(input: unknown, source = "catalog"): CatalogRecipe[] {
  const list = Array.isArray(input) ? input : [input];
  const recipes: CatalogRecipe[] = [];
  const problems: string[] = [];
  list.forEach((item, index) => {
    const result = catalogRecipeSchema.safeParse(item);
    if (result.success) recipes.push(result.data);
    else {
      const slug = (item as { slug?: string } | null)?.slug ?? `#${index}`;
      for (const issue of result.error.issues)
        problems.push(`${source} › ${slug}: ${issue.path.join(".")} ${issue.message}`);
    }
  });
  if (problems.length) throw new Error(`Invalid catalog recipes:\n${problems.join("\n")}`);
  return recipes;
}

export function buildCatalog(
  recipes: CatalogRecipe[],
  options: { publishAll?: boolean } = {},
): CatalogBuild {
  const issues: CatalogIssue[] = [];
  const seen = new Set<string>();
  for (const recipe of recipes) {
    if (seen.has(recipe.slug)) throw new Error(`Duplicate catalog slug: ${recipe.slug}`);
    seen.add(recipe.slug);
  }

  const recipeRows: string[] = [];
  const ingredientRows: string[] = [];
  const stepRows: string[] = [];

  for (const recipe of [...recipes].sort((a, b) => a.slug.localeCompare(b.slug))) {
    const parsed = parseIngredientList(recipe.ingredients);
    if (parsed.length === 0) issues.push({ slug: recipe.slug, message: "no ingredients parsed" });
    if (parsed.length < recipe.ingredients.length) {
      issues.push({
        slug: recipe.slug,
        message: `${recipe.ingredients.length - parsed.length} ingredient line(s) did not parse`,
      });
    }
    for (const ingredient of parsed) {
      // Water and ice sit in "Other" on purpose: they are listed but pre-marked as already on hand.
      if (
        ingredient.grocery_section === "Other" &&
        !ASSUMED_ON_HAND.has(ingredient.normalized_name)
      ) {
        issues.push({
          slug: recipe.slug,
          message: `"${ingredient.raw_text}" has no aisle (Other)`,
        });
      }
      if (
        ingredient.quantity === null &&
        !/\b(to taste|as needed|for serving)\b/i.test(ingredient.raw_text)
      ) {
        issues.push({ slug: recipe.slug, message: `"${ingredient.raw_text}" has no quantity` });
      }
    }

    const total = recipe.prep_minutes + recipe.cook_minutes;
    const publish = recipe.reviewed || options.publishAll ? "now()" : "null";
    recipeRows.push(
      `  ('seeded', ${str(recipe.slug)}, ${str(recipe.title)}, 'Pinched Kitchen', ${str(recipe.headnote)}, ${str(catalogImagePath(recipe.slug))}, ` +
        `${num(recipe.prep_minutes)}, ${num(recipe.cook_minutes)}, ${num(total)}, ${num(recipe.servings)}, ${arr(recipe.tags)}, null, ${publish})`,
    );

    parsed.forEach((ingredient, order) => {
      ingredientRows.push(
        `  (${str(recipe.slug)}, ${order}, ${num(ingredient.quantity)}, ${num(ingredient.quantity_max)}, ${str(ingredient.unit)}, ${str(ingredient.name)}, ` +
          `${str(ingredient.normalized_name)}, ${str(ingredient.preparation)}, ${str(ingredient.raw_text)}, ${str(ingredient.grocery_section)}, ${str(ingredient.group_label)})`,
      );
    });
    recipe.steps.forEach((step, index) =>
      stepRows.push(`  (${str(recipe.slug)}, ${index + 1}, ${str(step)})`),
    );
  }

  // A VALUES column that is null in every row is typed `text` by Postgres, so nullable numeric/text
  // columns are cast explicitly in the INSERT ... SELECT below.
  const slugs = [...seen].sort().map(str).join(", ");
  const sql = `-- Seeded recipe catalog. GENERATED by \`pnpm catalog:build\` from data/catalog/*.json — do not edit.
-- Safe to re-run: recipes upsert by slug; their ingredients and steps are replaced.
-- Recipes stay hidden (published_at is null) until a human marks them reviewed in the catalog JSON.

insert into public.recipes
  (source, slug, title, author, headnote, image_url, prep_minutes, cook_minutes, total_minutes, servings, tags, owner_id, published_at)
values
${recipeRows.join(",\n")}
on conflict (slug) where source = 'seeded' do update set
  title = excluded.title,
  author = excluded.author,
  headnote = excluded.headnote,
  image_url = excluded.image_url,
  prep_minutes = excluded.prep_minutes,
  cook_minutes = excluded.cook_minutes,
  total_minutes = excluded.total_minutes,
  servings = excluded.servings,
  tags = excluded.tags,
  published_at = coalesce(public.recipes.published_at, excluded.published_at);

delete from public.ingredients
  where recipe_id in (select id from public.recipes where source = 'seeded' and slug in (${slugs}));
delete from public.recipe_steps
  where recipe_id in (select id from public.recipes where source = 'seeded' and slug in (${slugs}));

insert into public.ingredients
  (recipe_id, owner_id, sort_order, quantity, quantity_max, unit, name, normalized_name, preparation, raw_text, grocery_section, group_label)
select r.id, null::text, v.sort_order::int, v.quantity::numeric, v.quantity_max::numeric, v.unit::text, v.name, v.normalized_name, v.preparation::text, v.raw_text, v.grocery_section, v.group_label::text
from (values
${ingredientRows.join(",\n")}
) as v(slug, sort_order, quantity, quantity_max, unit, name, normalized_name, preparation, raw_text, grocery_section, group_label)
join public.recipes r on r.source = 'seeded' and r.slug = v.slug;

insert into public.recipe_steps (recipe_id, owner_id, step_number, instruction)
select r.id, null::text, v.step_number::int, v.instruction
from (values
${stepRows.join(",\n")}
) as v(slug, step_number, instruction)
join public.recipes r on r.source = 'seeded' and r.slug = v.slug;
`;

  return { recipes, sql, issues };
}
